import { Product, Coupon, ShippingRule, TaxRule, Order, User, ProductReview } from '../types';
import { POUCH_IMAGES } from './productImages';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    title: 'Hapinoz Royal Garam Masala Pure Spice Blend (शाही गरम मसाला)',
    slug: 'hapinoz-royal-garam-masala-pure-spice-blend',
    sku: 'HPZ-BLN-001',
    description: 'Our iconic flagship blend in the signature clear stand-up zipper pouch. Handcrafted by slow-roasting 16 aromatic royal spices: green cardamom pods, mace (javitri), Ceylon cinnamon, star anise, nutmeg, black cardamom, cloves, and stone flowers (dagad phool). Freshly milled in small artisanal batches with zero fillers for rich, intoxicating aroma in curries, biryanis, and gravies.',
    short_description: 'Pure 16-spice royal Mughlai garam masala in aroma-lock clear zipper stand-up pouch.',
    price: 149,
    regular_price: 199,
    sale_price: 149,
    size: '100g',
    available_sizes: ['100g', '250g', '500g'],
    size_pricing: {
      '100g': { price: 149, regular_price: 199 },
      '250g': { price: 299, regular_price: 399 },
      '500g': { price: 549, regular_price: 749 },
    },
    stock_quantity: 65,
    stock_status: 'in_stock',
    category: 'Blended Masalas',
    tags: ['Garam Masala', 'Aroma Lock Pouch', 'Royal Blend', '16 Spices', 'Zero Fillers'],
    images: [
      POUCH_IMAGES.garamMasala,
      POUCH_IMAGES.heroBanner,
    ],
    rating: 5.0,
    reviews_count: 128,
    is_featured: true,
    is_active: true,
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'prod-002',
    title: 'Organic Lakadong Turmeric Powder (लकाडोंग हल्दी >7.5% Curcumin)',
    slug: 'organic-lakadong-turmeric-powder',
    sku: 'HPZ-SPC-002',
    description: 'Directly sourced from the pristine high-altitude Jaintia Hills of Meghalaya. Packed in our aroma-lock zipper pouch to shield its extraordinarily high natural curcumin potency (7.5% - 8.2%), radiant golden hue, and earthy herbal fragrance. Perfect for golden turmeric immunity milk, everyday dals, sabzis, and wellness recipes.',
    short_description: 'High-potency single-origin Lakadong turmeric with >7.5% natural curcumin in fresh clear pouch.',
    price: 129,
    regular_price: 179,
    sale_price: 129,
    size: '100g',
    available_sizes: ['100g', '250g', '500g'],
    size_pricing: {
      '100g': { price: 129, regular_price: 179 },
      '250g': { price: 249, regular_price: 349 },
      '500g': { price: 469, regular_price: 649 },
    },
    stock_quantity: 80,
    stock_status: 'in_stock',
    category: 'Pure Spice Powders',
    tags: ['High Curcumin', 'Lakadong', 'Meghalaya', 'Ayurvedic', 'Lab Certified', 'Golden Haldi'],
    images: [
      POUCH_IMAGES.turmeric,
      POUCH_IMAGES.heroBanner,
    ],
    rating: 5.0,
    reviews_count: 146,
    is_featured: true,
    is_active: true,
    created_at: '2026-08-12T11:30:00Z',
  },
  {
    id: 'prod-003',
    title: 'Royal Kashmiri Mirch Powder (कश्मीरी लाल मिर्च)',
    slug: 'royal-kashmiri-mirch-powder',
    sku: 'HPZ-SPC-003',
    description: 'Slow sun-dried, authentic stemless Kashmiri chillies pulverized using slow temperature-controlled milling under 40°C. Imparts an iconic rich ruby-red color and sweet aromatic warmth with gentle mild pungency (1,500 - 2,500 SHU). 100% natural, zero added oil, MSG, or artificial color.',
    short_description: 'Pure sun-dried Kashmiri chillies with deep natural ruby color and gentle warmth in zipper pouch.',
    price: 119,
    regular_price: 159,
    sale_price: 119,
    size: '100g',
    available_sizes: ['100g', '250g', '500g'],
    size_pricing: {
      '100g': { price: 119, regular_price: 159 },
      '250g': { price: 229, regular_price: 299 },
      '500g': { price: 429, regular_price: 569 },
    },
    stock_quantity: 58,
    stock_status: 'in_stock',
    category: 'Pure Spice Powders',
    tags: ['Pure Spices', 'Kashmiri Mirch', 'Micro Milled', 'Aroma Locked', 'Zero Colors', 'Mild Heat'],
    images: [
      POUCH_IMAGES.chilli,
      POUCH_IMAGES.heroBanner,
    ],
    rating: 4.9,
    reviews_count: 98,
    is_featured: true,
    is_active: true,
    created_at: '2026-08-15T09:00:00Z',
  },
  {
    id: 'prod-004',
    title: 'Slow-Roasted Cumin Powder (भुना जीरा पाउडर)',
    slug: 'slow-roasted-cumin-powder',
    sku: 'HPZ-SPC-004',
    description: 'Select crisp Rajasthan cumin seeds batch-roasted over slow flame until nutty, golden, and deeply aromatic before coarse cold-crushing. Elevates raitas, chaats, dahi bhalla, buttermilk, jaljeera, and hearty dal tadka with instant smoky aroma.',
    short_description: 'Batch-roasted golden cumin seeds crushed to deliver warm, smoky digestive notes.',
    price: 109,
    regular_price: 149,
    sale_price: 109,
    size: '100g',
    available_sizes: ['100g', '250g', '500g'],
    size_pricing: {
      '100g': { price: 109, regular_price: 149 },
      '250g': { price: 199, regular_price: 269 },
      '500g': { price: 379, regular_price: 499 },
    },
    stock_quantity: 64,
    stock_status: 'in_stock',
    category: 'Pure Spice Powders',
    tags: ['Bhuna Jeera', 'Roasted Cumin', 'Digestive', 'Smoky', 'Rajasthan Seeds', 'Chaat Masala'],
    images: [
      POUCH_IMAGES.jeera,
      POUCH_IMAGES.heroBanner,
    ],
    rating: 4.9,
    reviews_count: 82,
    is_featured: false,
    is_active: true,
    created_at: '2026-08-18T14:20:00Z',
  },
  {
    id: 'prod-005',
    title: 'Cold-Milled Coriander Powder (धनिया पाउडर)',
    slug: 'cold-milled-coriander-powder',
    sku: 'HPZ-SPC-005',
    description: 'Milled from plump green coriander seeds harvested from fertile fields of Madhya Pradesh. Cold-grinding ensures that the refreshing essential oils (linalool) remain locked inside each granule, providing thick gravy body and delicate floral citrus aroma.',
    short_description: 'Cold-milled green coriander seeds brimming with fresh citrusy essential oils in resealable pouch.',
    price: 89,
    regular_price: 119,
    sale_price: 89,
    size: '100g',
    available_sizes: ['100g', '250g', '500g'],
    size_pricing: {
      '100g': { price: 89, regular_price: 119 },
      '250g': { price: 149, regular_price: 199 },
      '500g': { price: 249, regular_price: 329 },
    },
    stock_quantity: 75,
    stock_status: 'in_stock',
    category: 'Pure Spice Powders',
    tags: ['Dhaniya Powder', 'Cold Milled', 'Madhya Pradesh', 'Essential Oils', 'Gravy Base'],
    images: [
      POUCH_IMAGES.coriander,
      POUCH_IMAGES.heroBanner,
    ],
    rating: 4.8,
    reviews_count: 67,
    is_featured: false,
    is_active: true,
    created_at: '2026-08-20T16:00:00Z',
  },
  {
    id: 'prod-006',
    title: 'Artisanal Dum Biryani & Pulao Masala (शाही बिरयानी मसाला)',
    slug: 'artisanal-dum-biryani-pulao-masala',
    sku: 'HPZ-BLN-006',
    description: 'Crafted with 14 royal spices slow-roasted and ground into a fragrant potli masala powder including saffron threads, mace, nutmeg, Ceylon cinnamon, star anise, black and green cardamom pods. Infuses authentic restaurant-grade fragrance into Hyderabadi and Awadhi Dum Biryanis.',
    short_description: 'Slow-roasted royal spice potli blend for authentic fragrant Dum Biryani and Pulao.',
    price: 159,
    regular_price: 219,
    sale_price: 159,
    size: '100g',
    available_sizes: ['100g', '250g', '500g'],
    size_pricing: {
      '100g': { price: 159, regular_price: 219 },
      '250g': { price: 319, regular_price: 429 },
      '500g': { price: 589, regular_price: 799 },
    },
    stock_quantity: 52,
    stock_status: 'in_stock',
    category: 'Blended Masalas',
    tags: ['Biryani Masala', 'Dum Biryani', 'Awadhi', 'Hyderabadi', 'Hand Pounded'],
    images: [
      POUCH_IMAGES.biryani,
      POUCH_IMAGES.heroBanner,
    ],
    rating: 5.0,
    reviews_count: 94,
    is_featured: true,
    is_active: true,
    created_at: '2026-08-22T08:15:00Z',
  },
  {
    id: 'prod-007',
    title: 'Fiery Guntur Teja Red Chilli Powder (गुंटूर तीखी मिर्च, 250g Pack)',
    slug: 'guntur-teja-red-chilli-powder-250g',
    sku: 'HPZ-SPC-007',
    description: 'Directly sourced from the black cotton soils of Guntur, Andhra Pradesh. Famous for its bold pungent heat (>70,000 SHU) and sharp aroma. Essential for Andhra spicy gravies, Kolhapuri rassa, Chettinad curries, and spicy pickles.',
    short_description: 'Authentic stemless Guntur Teja chillies for bold, pungent, fiery South & West Indian gravies.',
    price: 199,
    regular_price: 269,
    sale_price: 199,
    size: '250g',
    available_sizes: ['100g', '250g', '500g'],
    size_pricing: {
      '100g': { price: 109, regular_price: 149 },
      '250g': { price: 199, regular_price: 269 },
      '500g': { price: 369, regular_price: 499 },
    },
    stock_quantity: 45,
    stock_status: 'in_stock',
    category: 'Pure Spice Powders',
    tags: ['Guntur Teja', 'Fiery Hot', 'Andhra Spices', 'High Pungency', 'Authentic Red'],
    images: [
      POUCH_IMAGES.chilli,
      POUCH_IMAGES.heroBanner,
    ],
    rating: 4.9,
    reviews_count: 48,
    is_featured: false,
    is_active: true,
    created_at: '2026-08-25T11:00:00Z',
  },
  {
    id: 'prod-008',
    title: 'Pure Malabar Black Pepper Powder (काली मिर्च, 250g Pack)',
    slug: 'pure-malabar-black-pepper-250g',
    sku: 'HPZ-SPC-008',
    description: 'Milled from bold TGSEB peppercorns cultivated along Kerala’s Malabar coast. Slow-milled to safeguard its high piperine content, releasing intense woody heat, crisp pine notes, and complex citrus undertones upon seasoning.',
    short_description: 'Bold Malabar Tellicherry black pepper cold-ground for maximum piperine punch & aroma.',
    price: 279,
    regular_price: 379,
    sale_price: 279,
    size: '250g',
    available_sizes: ['100g', '250g', '500g'],
    size_pricing: {
      '100g': { price: 139, regular_price: 189 },
      '250g': { price: 279, regular_price: 379 },
      '500g': { price: 499, regular_price: 699 },
    },
    stock_quantity: 40,
    stock_status: 'in_stock',
    category: 'Pure Spice Powders',
    tags: ['Malabar', 'Tellicherry', 'Black Pepper', 'Piperine Rich', 'Kerala Spices'],
    images: [
      POUCH_IMAGES.garamMasala,
      POUCH_IMAGES.heroBanner,
    ],
    rating: 4.8,
    reviews_count: 53,
    is_featured: false,
    is_active: true,
    created_at: '2026-08-28T15:30:00Z',
  },
  {
    id: 'prod-009',
    title: 'Kadak Masala Chai Spice Powder (कड़क मसाला चाय, 250g Pack)',
    slug: 'kadak-masala-chai-blend-250g',
    sku: 'HPZ-BLN-009',
    description: 'The ultimate Indian morning ritual spice. Hand-crushed green cardamom, Kerala cloves, Ceylon cinnamon, black pepper, dry ginger (sonth), and nutmeg. A tiny pinch creates an invigorating, soothing cup of authentic Kadak Chai.',
    short_description: 'Crushed green cardamom, dry ginger, cloves, and cinnamon for the perfect Indian morning chai.',
    price: 339,
    regular_price: 459,
    sale_price: 339,
    size: '250g',
    available_sizes: ['100g', '250g', '500g'],
    size_pricing: {
      '100g': { price: 169, regular_price: 229 },
      '250g': { price: 339, regular_price: 459 },
      '500g': { price: 629, regular_price: 849 },
    },
    stock_quantity: 55,
    stock_status: 'in_stock',
    category: 'Blended Masalas',
    tags: ['Chai Masala', 'Tea Spice', 'Cardamom Rich', 'Ginger Sonth', 'Morning Brew'],
    images: [
      POUCH_IMAGES.biryani,
      POUCH_IMAGES.heroBanner,
    ],
    rating: 4.9,
    reviews_count: 91,
    is_featured: true,
    is_active: true,
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'prod-011',
    title: 'Amritsari Punjabi Chole Masala (अमृतसरी पंजाबी छोले मसाला)',
    slug: 'amritsari-punjabi-chole-masala',
    sku: 'HPZ-BLN-011',
    description: 'Authentic rich, tangy, and deeply aromatic Punjabi Chole & Chana masala spice blend. Slow-roasted dried pomegranate seeds (anardana), black cardamom, cassia cinnamon, cloves, dry mango (amchur), roasted cumin, and black pepper. Gives authentic dark Dhaba-style color and tangy aroma to chole bhature, pindi chana, and chickpea curries.',
    short_description: 'Tangy and dark authentic Amritsari Chole spice blend with real anardana & black cardamom.',
    price: 139,
    regular_price: 189,
    sale_price: 139,
    size: '100g',
    available_sizes: ['100g', '250g', '500g'],
    size_pricing: {
      '100g': { price: 139, regular_price: 189 },
      '250g': { price: 279, regular_price: 379 },
      '500g': { price: 519, regular_price: 699 },
    },
    stock_quantity: 60,
    stock_status: 'in_stock',
    category: 'Blended Masalas',
    tags: ['Chole Masala', 'Punjabi Chhole', 'Anardana', 'Pindi Chana', 'Dhaba Style', 'Aroma Locked'],
    images: [
      POUCH_IMAGES.choleMasala,
      POUCH_IMAGES.heroBanner,
    ],
    rating: 5.0,
    reviews_count: 112,
    is_featured: true,
    is_active: true,
    created_at: '2026-09-03T10:00:00Z',
  },
  {
    id: 'prod-010',
    title: 'Grand Kitchen Pantry Masala Combo Box (500g Value Pack)',
    slug: 'grand-kitchen-pantry-masala-combo-500g',
    sku: 'HPZ-CMB-010',
    description: 'The sacred trio for everyday cooking: Organic Lakadong Turmeric (250g) + Royal Kashmiri Mirch (250g) + Cold-Milled Dhaniya Powder (500g). Packed in individual aroma-lock stay-fresh pouches inside a gift box. Complete kitchen value saver!',
    short_description: 'Family Kitchen Value Box: 250g Haldi + 250g Kashmiri Mirch + 500g Dhaniya.',
    price: 549,
    regular_price: 749,
    sale_price: 549,
    size: '500g',
    available_sizes: ['250g', '500g'],
    size_pricing: {
      '250g': { price: 329, regular_price: 449 },
      '500g': { price: 549, regular_price: 749 },
    },
    stock_quantity: 32,
    stock_status: 'in_stock',
    category: 'Kitchen Combos',
    tags: ['Combo Pack', 'Family Pack', 'Trio Box', 'Kitchen Essentials', 'Value Saver'],
    images: [
      POUCH_IMAGES.heroBanner,
      POUCH_IMAGES.garamMasala,
    ],
    rating: 5.0,
    reviews_count: 149,
    is_featured: true,
    is_active: true,
    created_at: '2026-09-05T12:00:00Z',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'HAPINOZ10',
    discount_type: 'percentage',
    amount: 10,
    min_spend: 499,
    expiry_date: '2026-12-31',
    usage_limit: 1000,
    usage_count: 215,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'coup-2',
    code: 'SPICE50',
    discount_type: 'fixed',
    amount: 50,
    min_spend: 699,
    expiry_date: '2026-11-30',
    usage_limit: 500,
    usage_count: 142,
    is_active: true,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'coup-3',
    code: 'MASALA20',
    discount_type: 'percentage',
    amount: 20,
    min_spend: 999,
    expiry_date: '2026-10-31',
    usage_limit: 250,
    usage_count: 88,
    is_active: true,
    created_at: '2026-08-01T00:00:00Z',
  },
];

export const INITIAL_SHIPPING_RULES: ShippingRule[] = [
  {
    id: 'ship-1',
    title: 'Normal Delivery',
    cost: 49,
    free_threshold: 499,
    delivery_days: 'Up to 7 Days',
    is_active: true,
  },
];

export const INITIAL_TAX_RULES: TaxRule[] = [
  {
    id: 'tax-1',
    name: 'Spices & Food Goods GST (5%)',
    rate_percent: 5,
    is_compound: false,
    is_active: true,
  },
  {
    id: 'tax-2',
    name: 'Processed Masala Blends Concessional (12%)',
    rate_percent: 12,
    is_compound: false,
    is_active: false,
  },
];

export const SAMPLE_USERS: User[] = [
  {
    id: 'usr-admin-01',
    email: 'admin@hapinoz.com',
    full_name: 'Vikram Mehta (Spice Store Admin)',
    role: 'admin',
    phone: '+91 98765 43210',
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'usr-demo-02',
    email: 'ananya.sharma@example.com',
    full_name: 'Ananya Sharma',
    role: 'customer',
    phone: '+91 98111 22334',
    created_at: '2026-05-15T12:00:00Z',
  },
];

export const SAMPLE_REVIEWS: ProductReview[] = [
  {
    id: 'rev-1',
    product_id: 'prod-002',
    user_name: 'Dr. Ramesh Iyer',
    rating: 5,
    comment: 'The Lakadong turmeric has an unmistakable deep orange color and earthy aroma. Tests confirmed high curcumin. Wonderful quality from HAPINOZ!',
    created_at: '2026-08-20T09:12:00Z',
  },
  {
    id: 'rev-2',
    product_id: 'prod-001',
    user_name: 'Meenakshi Sundaram',
    rating: 5,
    comment: 'Gives my curries that sensational restaurant-red color without being scorching hot. Genuine Kashmiri chilli powder!',
    created_at: '2026-08-25T14:30:00Z',
  },
  {
    id: 'rev-3',
    product_id: 'prod-005',
    user_name: 'Chef Kabir Anand',
    rating: 5,
    comment: 'The Shahi Garam Masala is ground perfectly. You can actually smell the mace, green cardamom, and cloves. No artificial fillers.',
    created_at: '2026-08-27T11:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'HPZ-SPC-8821',
    user_id: 'usr-demo-02',
    customer_name: 'Ananya Sharma',
    customer_email: 'ananya.sharma@example.com',
    customer_phone: '+91 98111 22334',
    items: [
      {
        id: 'item-1',
        product_id: 'prod-001',
        title: 'Royal Kashmiri Mirch Powder (250g)',
        price: 249,
        quantity: 2,
        image: POUCH_IMAGES.chilli,
        total: 498,
      },
      {
        id: 'item-2',
        product_id: 'prod-002',
        title: 'Organic Lakadong Turmeric Powder (250g)',
        price: 299,
        quantity: 1,
        image: POUCH_IMAGES.turmeric,
        total: 299,
      },
    ],
    subtotal: 797,
    discount: 79.7,
    shipping_fee: 0,
    tax_amount: 35.87,
    total: 753.17,
    coupon_code: 'HAPINOZ10',
    status: 'delivered',
    payment_status: 'paid',
    payment_method: 'Razorpay UPI',
    razorpay_order_id: 'order_live_938192019',
    razorpay_payment_id: 'pay_live_891029381',
    shipping_address: {
      id: 'addr-1',
      full_name: 'Ananya Sharma',
      phone: '+91 98111 22334',
      address_line1: 'Flat 402, Lotus Orchid, Indiranagar',
      address_line2: '100ft Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      postal_code: '560038',
      country: 'India',
      is_default: true,
      type: 'shipping',
    },
    tracking_number: 'BLRDTC-892182910',
    created_at: '2026-08-28T14:20:00Z',
  },
  {
    id: 'ord-1002',
    order_number: 'HPZ-SPC-8822',
    user_id: 'usr-guest-03',
    customer_name: 'Siddharth Roy',
    customer_email: 'siddharth.roy@example.com',
    customer_phone: '+91 97234 56789',
    items: [
      {
        id: 'item-3',
        product_id: 'prod-005',
        title: 'Royal Shahi Garam Masala Blend (100g)',
        price: 279,
        quantity: 2,
        image: POUCH_IMAGES.garamMasala,
        total: 558,
      },
      {
        id: 'item-4',
        product_id: 'prod-003',
        title: 'Pure Malabar Black Pepper Powder (150g)',
        price: 199,
        quantity: 1,
        image: POUCH_IMAGES.garamMasala,
        total: 199,
      },
    ],
    subtotal: 757,
    discount: 50,
    shipping_fee: 0,
    tax_amount: 35.35,
    total: 742.35,
    coupon_code: 'SPICE50',
    status: 'processing',
    payment_status: 'paid',
    payment_method: 'Razorpay Cards',
    razorpay_order_id: 'order_live_938192994',
    razorpay_payment_id: 'pay_live_891029443',
    shipping_address: {
      id: 'addr-2',
      full_name: 'Siddharth Roy',
      phone: '+91 97234 56789',
      address_line1: 'Villa 12, Silver Oak Green, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      postal_code: '400050',
      country: 'India',
      is_default: true,
      type: 'shipping',
    },
    tracking_number: 'BLUEDART-8821039',
    created_at: '2026-09-02T10:15:00Z',
  },
];
